// <auto-generated />
namespace DOAN_TINTUC24H.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updatetacgia : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatetacgia));
        
        string IMigrationMetadata.Id
        {
            get { return "202212050701441_updatetacgia"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
